black = "#51576d"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#b5bfe2"

bri_black = "#626880"
bri_red = "#e78284"
bri_green = "#a6d189"
bri_yellow = "#e5c890"
bri_blue = "#8caaee"
bri_magenta = "#f4b8e4"
bri_cyan = "#81c8be"
bri_white = "#a5adce"

surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
text = "#c6d0f5"
