black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

bri_black = "#444b6a"
bri_blue = "#7da6ff"
bri_cyan = "#0db9d7"
bri_green = "#b9f27c"
bri_magenta = "#bb9af7"
bri_red = "#ff7a93"
bri_white = "#acb0d0"
bri_yellow = "#ff966c"

base = "#222436"
text = "#a9b1d6"