[manager]
prepend_keymap = [
{ on = [ "r" ], run = "rename --cursor=end", desc = "Rename" },
{ on = [ "<C-r>" ], run = "redo", desc = "Redo"},
{ on = [ "<C-o>" ], run = "plugin toggle-pane max-preview", desc = "Toggle Preview_max"},
{ on = [ "T" ], run = "plugin toggle-pane min-parent", desc = "Toggle parent"},
{ on = [ "l" ], run = "plugin smart-enter", desc = "Enter dir/Open file" },
{ on = [ "J" ], run = "arrow 5", desc = "Move cursor down" },
{ on = [ "K" ], run = "arrow -5", desc = "Move cursor up" },
{ on = [ "<C-k>" ], run = "seek -10", desc = "Seek up"},
{ on = [ "<C-j>" ], run = "seek 10", desc = "Seek down"},
{ on = [ "<C-w>" ], run = "close", desc = "Close current tab"},
{ on = [ "g","m" ], run = "cd E:/dot", desc = "Goto dotfile dir" },
{ on = [ "g","c" ], run = "cd ~/AppData", desc = "Goto config dir" },
{ on = [ "g","p" ], run = "cd E:/proj", desc = "Goto proj dir" },
{ on = [ "g","t" ], run = "cd E:/proj/cntest", desc = "Goto test dir" },
{ on = [ "g","b" ], run = "cd E:/doc/books", desc = "Goto book dir" },
{ on = [ "g","d" ], run = "cd ~/Downloads", desc = "Goto download dir" },
{ on = [ "g","n" ], run = "cd E:/daily", desc="Goto note dir" },
{ on = [ "C","Z" ], run = "plugin ouch zip", desc="zip" },
{ on = [ "g","C" ], run = "cd C:/", desc = "Goto C disk" },
{ on = [ "g","D" ], run = "cd D:/", desc = "Goto D disk" },
{ on = [ "g","E" ], run = "cd E:/", desc = "Goto E disk" },
]

append_keymap = [
{ on = [ "R" ], run = "rename --cursor=before_ext", desc = "Rename before_ext" },
{ on = [ "u" ], run = "undo", desc = "Undo the last operation"},
{ on = [ "<C-a>" ], run = "select_all --state=none", desc = "Select all file on current directory"},
]
