[colors.primary]
background = "#222436"
foreground = "#a9b1d6"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff966c"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#9ece6a"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#ff966c"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#acb0d0"
